### PR TITLE
Start using the icon parameter of buttons

### PR DESCRIPTION
**Pull request by carakas**
This will fix the font changing to the icon-font when we want to set an icon in the button

### CODE REVIEW

**Comment by WouterSioen** [comment]
looks good, will you add a new tag and update the main Framework repository after this is merged?

**Comment by carakas** [comment]
I will first also add it to the example bundle before I update the main Framework repository

**Comment by WouterSioen** [comment]
just saying so you don't forget it ;)

**Comment by tijsverkoyen** [comment]
:shipit:

**Pull request merged**
